- name: functions
  hosts: local
  connection: local
  vars:
    persons: "laji,sujay,minnu,bujji"
  tasks:
  - name: functions in ansible
    ansible.builtin.debug:
      msg : "hello {{ guru | default('heart') }}"

  - name: print persons
    ansible.builtin.debug:
      msg : "hello {{ persons | split(',') }}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10HR
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "Course Info: {{ course | dict2items  }}"

  - name: convert list into map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10HR'}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "Course Info: {{ course | items2dict  }}"

  - name: convert to uppercase
    vars:
      name: "Sivakumar Reddy M"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"

  - name: convert to lowercase
    vars:
      name: "Sivakumar Reddy M"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"

  - name: check IP address is valid or not
    vars:
      ip: "192.168.1.1"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}"