- name: functions demo
  hosts: localhost
  connection: local
  vars:
    persons: "Ramesh,Suresh,Raheem,Joseph"
  tasks:

    - name: Check undefined variable
      ansible.builtin.debug:
        msg: "Hello, {{ person | default('Ramesh') }}"

    - name: Print each name individually
      ansible.builtin.debug:
        msg: "Hello {{ item }}"
      loop: "{{ persons.split(',') }}"

    - name: Convert map into list
      vars:
        course:
          name: ansible
          duration: 10HR
          trainer: Guru
      ansible.builtin.debug:
        msg: "Course Info as list: {{ course | dict2items }}"

    - name: Convert list into map
      vars:
        course_list:
          - {'key': 'name', 'value': 'ansible'}
          - {'key': 'duration', 'value': '10HR'}
          - {'key': 'trainer', 'value': 'Guru'}
      ansible.builtin.debug:
        msg: "Course Info as dict: {{ course_list | items2dict }}"

    - name: Convert name to uppercase
      vars:
        name: "Guru"
      ansible.builtin.debug:
        msg: "Uppercase: {{ name | upper }}"

    - name: Convert name to lowercase
      vars:
        name: "Guru"
      ansible.builtin.debug:
        msg: "Lowercase: {{ name | lower }}"

    - name: Check if IP address is valid
      vars:
        ip: "192.168.1.1"
      ansible.builtin.debug:
        msg: >
          {% if ip | ipaddr %}
            {{ ip }} is a valid IP
          {% else %}
            {{ ip }} is not a valid IP
          {% endif %}

# Ah! The playbook ran fine except for the last task (IP validation).
#Failed to import the required Python library (netaddr)


# For Amazon Linux / RHEL / CentOS
#sudo yum install python3-netaddr -y

# Or using pip
#pip3 install netaddr --user
